name: Github packages publish

on: workflow_dispatch

env:
  BUILTIN_PYTHON_VERSION: 3.10.13

jobs:
  publish:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --builtin_python=true
      - run: npx @mapbox/node-pre-gyp build -j max
      - run: node scripts/pympip install setuptools==65.1.1
      - run: npx @mapbox/node-pre-gyp package
      - run: npx @mmomtchev/node-pre-gyp-github publish
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
