name: Github packages publish

on: workflow_dispatch

env:
  BUILTIN_PYTHON_VERSION: 3.12.2

jobs:
  publish:
    runs-on: ${{ matrix.platform }}
    
    strategy:
      matrix:
        platform: [ubuntu-20.04, windows-2019, macos-12, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install conan
        uses: turtlebrowser/get-conan@main
      - name: Get conan home
        id: conan_home
        shell: bash
        run: echo CONAN_HOME=`conan config home` >> "$GITHUB_OUTPUT"
      - name: Cache conan artifacts
        uses: actions/cache@v4
        with:
          path: ${{ steps.conan_home.outputs.CONAN_HOME }}
          key: ${{ runner.os }}-${{ runner.arch }}
      - run: npm install --ignore-scripts
      - run: npx @mapbox/node-pre-gyp configure --builtin_python=true
      - run: npx @mapbox/node-pre-gyp build -j max
      - run: node scripts/pympip install setuptools==69.0.3
      - run: npx @mapbox/node-pre-gyp package
      - run: npx @mmomtchev/node-pre-gyp-github publish
        env:
          NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
